### ISSUE TITLE
cot数据微调

### ISSUE THREAD

**Issue by vincentlbj** [zhiqix/NL2GQL#1]
请问下你们cot格式的数据是怎么进行微调的呀

**Comment by zhiqix** [comment]
hello，这部分数据是作为微调输出的一部分，使模型输出推理后输出nGQL语句。

**Comment by vincentlbj** [comment]
加载了你们的lora模型后，prompt应该怎么写，我直接输入这个语句返回的结果是这样的：
![16889829697119](https://github.com/zhiqix/NL2GQL/assets/11678803/5c95dd82-3869-4c70-90ad-e7bb849e0fce)

**Comment by vincentlbj** [comment]
哦哦，想问下你们reason字段的数据是怎么生成的呀，还是通过gpt吗

**Comment by zhiqix** [comment]
> 哦哦，想问下你们reason字段的数据是怎么生成的呀，还是通过gpt吗

一开始试过GPT，但是效果不好。训练数据不是本身就包含正确的ngql吗，所以只需要通过规则对ngql进行提取就行啦

**Comment by vincentlbj** [comment]
好的好的，谢谢
