### ISSUE TITLE
数据疑问

### ISSUE THREAD

**Issue by YLiberals** [zhiqix/NL2GQL#2]
因为之前没有接触过NebulaGraph，不知道是不是自己操作不当或者理解错误。在nba的ngql文件中，看到了bachelor实体，但是没有发现相关的数据；另外还有like关系也没有相关的数据，还有想确认一下edge_follow.csv是不是teammate关系的文件，因为teammate关系包含start_year和end_year，但是在文件中也没有发现相关的

**Comment by zhiqix** [comment]
感谢提出问题！，NebulaGraph给的示例程序里有两种类型的schema，由于我们的疏忽确实传错了版本，您的理解是对的，我们会尽快重新上传正确版本的data文件，非常感谢！

**Comment by HEYU322** [comment]
您好，我们已经更新了正确版本的数据！

**Comment by YLiberals** [comment]
> 感谢提出问题！，NebulaGraph给的示例程序里有两种类型的schema，由于我们的疏忽确实传错了版本，您的理解是对的，我们会尽快重新上传正确版本的data文件，非常感谢！

好的，谢谢
